### ISSUE TITLE
problem with server

### ISSUE THREAD

**Issue by lexusburn** [jtangelder/denon-remote#1]
Hello,

i had tried your denon-remote and it works well with my denon x2000 if i use cli.
But if i use the server i only get a static page (with status not connected) and this output:

(function() { var Denon, socket; Denon = (function() { return { connect: function(host, port) { return socket.emit('denon.connect', { host: host, port: port }); }, command: function(cmd, params) { return socket.emit('denon.command', { cmd: cmd, params: params || [] }); }, exec: function(cmd, params) { return socket.emit('denon.exec', { cmd: cmd, param: param || "" }); } }; })(); socket = io.connect(); socket.on('connect', function(data) { return Denon.connect('192.168.2.170', 23); }); socket.on('denon.connected', function(data) { console.log('denon.connected!'); $("#data-connected").text("Connected"); Denon.command('power'); Denon.command('input'); Denon.command('volume'); return Denon.command('info'); }); socket.on('denon.response', function(data) { var index, value, _ref, _results; switch (data.cmd) { case 'power': return $("#data-power").text(data.value); case 'input': return $("#data-input").text(data.value); case 'volume': return $("#data-volume").text(data.value); case 'info': _ref = data.value; _results = []; for (index in _ref) { value = _ref[index]; if (index === "0") { $("#data-info").empty(); _results.push($("#data-info-title").text(value)); } else { _results.push($("#data-info").append("" + value + "\n")); } } return _results; break; default: return console.log('response', data); } }); }).call(this); 

can you please help?
if you need some informations about module versions let me know.

**Comment by hamadyne** [comment]
Tried verifying this myself: I get the exact same issue. Jade has updated its filters, code should use `:coffee-script` as a proper filter.

However, even with this in place, the code still shows up on the page, and connections to the Denon receiver fail. There needs to be an additional `script` tag added above the `:coffee-script` tag.

**Comment by jtangelder** [comment]
I've just updated the repo and did a rewrite of the codebase. It now is a simple CLI..! I will close this issue, since it has become obsolete. 🙃
