### ISSUE TITLE
I got some error 

### ISSUE THREAD

**Issue by hamwong** [jtangelder/denon-remote#8]
Hi, I got some error when run denon, I run it at raspberry, any idea?

/root/.npm-global/lib/node_modules/denon/index.js:12
denon.on('connect', ()=> {
                     ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by jtangelder** [comment]
Sounds like your node version isn't up to date! The codebase uses arrow functions and some other es6 syntax, which is only available in node since the last year or so.

**Comment by hamwong** [comment]
hi, thanks for your reply, actually I am a newbie on linux, and node,
I took a while to google how to upgrade the no de, I finally get it upgrade by nvm,
after that, I just turn out nothing....

[20:25:03] root@openHABianPi:~/.npm-global/lib/node_modules# node denon
[20:25:06] root@openHABianPi:~/.npm-global/lib/node_modules# node denon

am I doing anything wrong? thank you for spending your time on me.

**Comment by hamwong** [comment]
thanks, you are right, I got it works now
I am sorry as I am newbie on linux and node, thanks for your time,
I got 1 extra question, how do keep ask denon response to you by telnet?
when I telnet to denon, I only able get first command be response, after that, telnet still receive status update from denon but which no longer take order from telnet,
I checked with wireshark packet from putty is correct with x0d at the end of command. do you mind tell me how do you make this work?
